### ISSUE TITLE
Document additional dependency requirements

### ISSUE THREAD

**Issue by fogti** [drobilla/zix#2]
* `glib`

https://github.com/NixOS/nixpkgs/blob/750f196b393267d4d2bc6ce625767754287d72b2/pkgs/development/libraries/zix/default.nix

**Comment by drobilla** [comment]
Zix doesn't depend on glib (only a few benchmarks do) or reuse (which is just a test for maintenance).  The default build options should work fine without both, and nothing user-visible will be missing.

**Comment by fogti** [comment]
Actually, I am unable to build it without `reuse`:
```
The Meson build system
Version: 0.63.1
Source dir: /build/source
Build dir: /build/source/build
Build type: native build
Project name: zix
Project version: 0.2.0
C compiler for the host machine: gcc (gcc 11.3.0 "gcc (GCC) 11.3.0")
C linker for the host machine: gcc ld.bfd 2.38
Host machine cpu family: x86_64
Host machine cpu: x86_64
Checking if "clock_gettime" compiles: YES 
Checking if "mlock" compiles: YES 
Checking if "posix_memalign" compiles: YES 
Checking if "sem_timedwait" compiles: YES 
Run-time dependency threads found: YES
Program autoship found: NO
Program reuse found: NO

meson.build:227:2: ERROR: Program 'reuse' not found or not executable
```

Due to
https://github.com/drobilla/zix/blob/afc6ef7e54988fd68f33df21ec2a220e6bfc49f4/meson.build#L227

Because I want to run tests, and the conditional directly below indicates that the `required` condition is likely wrong.

**Comment by drobilla** [comment]
Don't Do That Then™

See https://drobilla.net/2022/08/16/on-meson-features.html

I guess I will put this under the strict flag as well so packagers stop doing this, but in any case, that's how feature options work.  You asked for it to fail, and the default is not `enabled` for a reason.  If you want it to work despite a dependency not being present, then you want `auto` (which is the default).

**Comment by drobilla** [comment]
(Also, please always include at least the actual commands you are running)

**Comment by drobilla** [comment]
"Fixed" in a029351

**Comment by eli-schwartz** [comment]
@drobilla

To be fair, I think that it actually makes a lot of sense to gate regular tests behind a test option, and lint tests behind an additional option. So this may be for the best. :)

**Comment by drobilla** [comment]
@eli-schwartz Yeah, I've been doing that and agree it's generally a good idea.

... in this specific sort of case anyway.  In general, I stand behind the above post and will continue to push back against this weird anti-feature-option thing.  It's dangerous at scale, and just plain shitty behaviour to throw away a developer's defaults, explicitly enable things so the build won't succeed if something is missing, then complain about it when exactly what they asked for happens.

More granular features is absolutely fine.  Sacrificing the coherence of the feature system to satisfy weird bleeding edge distro egos or whatever is very not fine, and I will absolutely die on that hill :)

**Comment by eli-schwartz** [comment]
Yeah, I don't get the argument that it's somehow "wrong" to use required because "you check it with found() so the condition is likely wrong". That's literally how options work...

I think distros often do have a vested interest in guaranteeing that "integration and smoke tests" run during packaging though :) so I suspect that people just aren't very clear on what constitutes that vs. lint.

Aside: the python packaging ecosystem is a total trash heap, and I lost count many years ago of the number of times I had to sed out options from a pytest config file that forced it to also run isort, flake8, cov(erage), black... same basic story, but there it's outright impossible to run integration tests while avoiding linters. So patching the source code it is...

**Comment by drobilla** [comment]
Makes sense.  I've been a bit pissy at packagers lately due to this feature option stuff, but it's definitely important for them (and anyone deploying) to be able to run tests.  I hadn't really put any thought into that area yet - they're all just tests of some sort of another to me.  The system I'm working on does or doesn't have them... whatever (naturally my main dev machine and at least one test docker image does, so it's known they run _somewhere_ which is all that matters).

Test categorization is hard in general though.  I guess "lint" covers source code and metadata checking stuff pretty decently, but honestly I have an ergonomic (and/or arguably lazy) incentive to just mash any and all "for the developer" things, from warnings to linters, under a single `strict` option: I type (or at least dig out of history) a lot of `meson setup` commands every day, so I'm really averse to adding even more almost-ever-present `-Dspam=true`.

I guess that makes "strict" arguably misleading, but oh well.

... I'd be less averse to more `-Dspam` if things like `meson setup -Dtests -Dlint build` worked (ala `gcc -DSOMETHING` but typed) though :)  Has that idea come up?

**Comment by eli-schwartz** [comment]
I think strict is an okay name for what some people would call a "developer build", which is probably the only distinction worth making. Those are typically there as a catch-all "the project developer needs to run this" and don't need finely broken out, granular option selection.

**Comment by fogti** [comment]
oh guess I misunderstood the intended mechanism at that point.

**Comment by drobilla** [comment]
@zseri No worries, we're way off on a tangent now, not really about just this issue
