### ISSUE TITLE
Type mismatch, cannot assign value

### ISSUE THREAD

**Issue by jimwang118** [drobilla/zix#8]
After the BenchmarkTime definition is modified, the return value type of the bench_start() function called in the tree_bench.c and dict_dench.c files does not match, and the following error occurs.
```
../src/v0.4.2-a17f373b9a/benchmark/tree_bench.c(90): error C2440: 'initializing': cannot convert from 'BenchmarkTime' to 'timespec'
../src/v0.4.2-a17f373b9a/benchmark/tree_bench.c(102): error C2440: 'initializing': cannot convert from 'BenchmarkTime' to 'timespec'
```
Please fix the definition type of the variable that receives the return value.

**Comment by drobilla** [comment]
? This doesn't make sense on several levels at once.

The result of `bench_start()` is always assigned to a `BenchmarkTime` variable.  This change was made _before_ the type change you're referring to.

You seem to have applied a broken patch for an older commit (https://github.com/microsoft/vcpkg/blob/bdcf0c2dabd9c9081e3e1d6c662983580083b4bd/ports/zix/fix-win32.patch).  I'm not sure exactly what you've applied it to though, since the git history must have also been messed with somehow: judging by the line number, the version of `tree_bench.c` you're building can't be newer than 0d200a5, which is well before the `BenchmarkTime` change.  In other words, there is no commit in zix where these errors are possible, even with changes to `bench.h`.

Please don't file upstream issues for things you broke.
